// ANCHOR: all
// ANCHOR: command
$ forge test --allow-failure
// ANCHOR_END: command
// ANCHOR: output
Compiling 1 files with 0.8.10
Compiler run successful

Running 1 test for src/test/Safe.t.sol:SafeTest
[FAIL. Counterexample: calldata=0x215a2f20ffffffffffffffffffffffff0000000000000000000000000000000000000000, args=[115792089237316195423570985007226406215939081747436879206741300988257197096960]] testWithdraw(uint256) (runs: 1, μ: 6173, ~: 6173)
Test result: FAILED. 0 passed; 1 failed; finished in 290.00µs
// ANCHOR_END: output
// ANCHOR_END: all
